warnings_are_errors: false

language: r

os:
  - linux
  - osx

r:
  - release

branches:
  only:
  - master
    
sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

before_deploy:
  # Get PKGVER
  - 'export PKGVER=$(sed -n "s/Version: *\([^ ]*\)/\1/p" DESCRIPTION)'
  # CHECK version type by counting dots (flaky)
  - 'export RELEASE=$(grep -o \\. <<< $PKGVER | wc -w)'
  - "echo $RELEASE"
  # Build binary and remove the source archive
  - "R CMD INSTALL --build ggplotFL_$PKGVER.tar.gz"
  - "rm ggplotFL_$PKGVER.tar.gz"
  # Look for packages
  - "export RELEASE_PKG_FILE=$(ls ggplotFL*gz)"
  - "echo $RELEASE_PKG_FILE"

deploy:
  provider: releases
  api_key:
    secure: QrWCUrkEVOwPitBzGoIoK8zp2Mk4SL0KTnygW9YtVwFCe+vkbEAfvRpRRQ9IvjPUberQT1WvysWr/oM232QtL+g7TeEad0uB5oLMrGq6lyUBgaUnkzRShIKMbUzXOH3i2EW4Bv2mUaKf02nkiRNcNIG0t3SBfwbgMHwhf/VWATc=
  file: $RELEASE_PKG_FILE
  skip_cleanup: true
  draft: true
  on:
    repo: flr/ggplotFL
    # condition: "$RELEASE=2"
    # condition: $RELEASE =~ ^[0-9]+\.[0-9]+\.[0-9]+
