language: r

env:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

warnings_are_errors: false

os:
  - linux
  - osx

r:
  - release

branches:
  only:
  - master
    
sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  # Get PKGVER
  - 'export PKGVER=$(sed -n "s/Version: *\([^ ]*\)/\1/p" DESCRIPTION)'
  - 'export REL=$(echo $PKGVER | grep -o "\." | grep -c "\.")'
  - "echo $PKGVER $REL"
  # Build binary and remove the source archive
  - "R CMD INSTALL --build ggplotFL_$PKGVER.tar.gz"
  - "rm ggplotFL_$PKGVER.tar.gz"
  # Look for packages
  - "export RELEASE_PKG_FILE=$(ls ggplotFL*gz)"
  - "echo $RELEASE_PKG_FILE"

deploy:
  provider: releases
  api_key:
    secure: jyIwj8m46vTrxdNiqwc8NHIpv4nhvtJOc/bIwCiuDpiacU3HFQjoixU3xyFjBOyjq23Nn1q5GB560yi2vTlIVxvbsn2+7fAhicwbUIxXk7IKP952twMQcB2iuJL4KJGpe16cMHXFehsytgsJOnDbEaSH1CVa9PM2V/mmm2UwbUs=
  file: $RELEASE_PKG_FILE
  skip_cleanup: true
  draft: true
  on:
    repo: flr/ggplotFL
    condition: $REL = "2"
